In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("scraped_data_nba_games.csv", index_col=0)

In [3]:
df.shape

(17772, 150)

In [4]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,teams_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,34.0,87.0,0.391,8.0,31.0,0.258,18.0,22.0,...,51.5,33.0,200.0,110.0,OKC,110,1,2020,2020-08-01,False
1,240.0,240.0,41.0,77.0,0.532,10.0,26.0,0.385,18.0,24.0,...,50.0,35.2,182.0,125.0,UTA,94,0,2020,2020-08-01,True
2,240.0,240.0,35.0,89.0,0.393,10.0,27.0,0.370,23.0,28.0,...,50.0,28.3,137.0,112.0,BOS,117,1,2016,2016-01-15,False
3,240.0,240.0,42.0,96.0,0.438,14.0,30.0,0.467,19.0,29.0,...,30.4,33.3,135.0,124.0,PHO,103,0,2016,2016-01-15,True
4,240.0,240.0,40.0,92.0,0.435,14.0,40.0,0.350,9.0,14.0,...,33.3,38.6,154.0,113.0,OKC,105,1,2017,2016-11-16,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,41.0,86.0,0.477,12.0,32.0,0.375,22.0,30.0,...,53.2,40.6,227.0,118.0,WAS,107,0,2021,2021-01-08,True
17768,240.0,240.0,49.0,96.0,0.510,13.0,37.0,0.351,13.0,21.0,...,25.0,32.6,141.0,135.0,GSW,97,1,2020,2020-01-14,True
17769,240.0,240.0,39.0,87.0,0.448,9.0,32.0,0.281,10.0,13.0,...,11.8,40.4,210.0,106.0,DAL,124,0,2020,2020-01-14,False
17770,240.0,240.0,45.0,96.0,0.469,13.0,33.0,0.394,13.0,16.0,...,46.9,31.5,168.0,123.0,HOU,140,1,2017,2016-12-30,False
17771,240.0,240.0,45.0,81.0,0.556,14.0,40.0,0.350,36.0,43.0,...,32.2,33.8,162.0,143.0,LAC,116,0,2017,2016-12-30,True

In [5]:
df = df.sort_values('date')

In [6]:
df = df.reset_index(drop=True)

In [7]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,teams_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
3,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
4,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,40.0,91.0,0.440,15.0,43.0,0.349,12.0,15.0,...,25.8,32.4,205.0,120.0,BOS,97,1,2022,2022-06-10,True
17768,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [8]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [9]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,teams_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
2,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
3,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
4,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,40.0,91.0,0.440,15.0,43.0,0.349,12.0,15.0,0.800,...,25.8,32.4,205.0,120.0,BOS,97,1,2022,2022-06-10,True
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [10]:
df.columns.values.tolist()

['mp',
 'fg',
 'fga',
 'fg%',
 '3p',
 '3pa',
 '3p%',
 'ft',
 'fta',
 'ft%',
 'orb',
 'drb',
 'trb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 '+/-',
 'ts%',
 'efg%',
 '3par',
 'ftr',
 'orb%',
 'drb%',
 'trb%',
 'ast%',
 'stl%',
 'blk%',
 'tov%',
 'usg%',
 'ortg',
 'drtg',
 'mp_max',
 'mp_max.1',
 'fg_max',
 'fga_max',
 'fg%_max',
 '3p_max',
 '3pa_max',
 '3p%_max',
 'ft_max',
 'fta_max',
 'ft%_max',
 'orb_max',
 'drb_max',
 'trb_max',
 'ast_max',
 'stl_max',
 'blk_max',
 'tov_max',
 'pf_max',
 'pts_max',
 '+/-_max',
 'ts%_max',
 'efg%_max',
 '3par_max',
 'ftr_max',
 'orb%_max',
 'drb%_max',
 'trb%_max',
 'ast%_max',
 'stl%_max',
 'blk%_max',
 'tov%_max',
 'usg%_max',
 'ortg_max',
 'drtg_max',
 'teams',
 'total',
 'home',
 'mp_opp',
 'fg_opp',
 'fga_opp',
 'fg%_opp',
 '3p_opp',
 '3pa_opp',
 '3p%_opp',
 'ft_opp',
 'fta_opp',
 'ft%_opp',
 'orb_opp',
 'drb_opp',
 'trb_opp',
 'ast_opp',
 'stl_opp',
 'blk_opp',
 'tov_opp',
 'pf_opp',
 'pts_opp',
 '+/-_opp',
 'ts%_opp',
 'efg%_opp',
 '3par_opp',
 'ftr_opp',
 'orb%_opp',
 'drb%_opp',
 'trb%_opp',
 'ast%_opp',
 'stl%_opp',
 'blk%_opp',
 'tov%_opp',
 'usg%_opp',
 'ortg_opp',
 'drtg_opp',
 'mp_max_opp',
 'mp_max_opp.1',
 'fg_max_opp',
 'fga_max_opp',
 'fg%_max_opp',
 '3p_max_opp',
 '3pa_max_opp',
 '3p%_max_opp',
 'ft_max_opp',
 'fta_max_opp',
 'ft%_max_opp',
 'orb_max_opp',
 'drb_max_opp',
 'trb_max_opp',
 'ast_max_opp',
 'stl_max_opp',
 'blk_max_opp',
 'tov_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 '+/-_max_opp',
 'ts%_max_opp',
 'efg%_max_opp',
 '3par_max_opp',
 'ftr_max_opp',
 'orb%_max_opp',
 'drb%_max_opp',
 'trb%_max_opp',
 'ast%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'tov%_max_opp',
 'usg%_max_opp',
 'ortg_max_opp',
 'drtg_max_opp',
 'teams_opp',
 'total_opp',
 'home_opp',
 'season',
 'date',
 'won']

In [11]:
def add_target(team):
    team['target'] = team["won"].shift(-1)
    return team

df = df.groupby("teams", group_keys=False).apply(add_target)

In [12]:
df[df["teams"] == 'LAL']

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,teams_opp,total_opp,home_opp,season,date,won,target
24,240.0,35.0,90.0,0.389,9.0,34.0,0.265,32.0,35.0,0.914,...,31.3,206.0,119.0,MIN,112,0,2016,2015-10-28,False,False
48,240.0,41.0,89.0,0.461,11.0,34.0,0.324,21.0,27.0,0.778,...,33.3,200.0,112.0,SAC,132,1,2016,2015-10-30,False,False
79,240.0,31.0,85.0,0.365,10.0,34.0,0.294,21.0,28.0,0.750,...,24.0,155.0,105.0,DAL,103,0,2016,2015-11-01,False,False
104,240.0,36.0,86.0,0.419,6.0,26.0,0.231,31.0,38.0,0.816,...,27.5,193.0,115.0,DEN,120,0,2016,2015-11-03,False,True
151,240.0,33.0,78.0,0.423,7.0,23.0,0.304,31.0,40.0,0.775,...,27.2,116.0,109.0,BRK,98,1,2016,2015-11-06,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17469,240.0,49.0,92.0,0.533,6.0,20.0,0.300,14.0,21.0,0.667,...,46.1,201.0,121.0,DEN,129,0,2022,2022-04-03,False,False
17502,240.0,39.0,86.0,0.453,9.0,29.0,0.310,23.0,30.0,0.767,...,37.5,155.0,111.0,PHO,121,1,2022,2022-04-05,False,False
17526,240.0,37.0,83.0,0.446,9.0,32.0,0.281,29.0,38.0,0.763,...,31.6,300.0,114.0,GSW,128,1,2022,2022-04-07,False,True
17538,240.0,41.0,82.0,0.500,9.0,31.0,0.290,29.0,39.0,0.744,...,31.6,132.0,125.0,OKC,101,0,2022,2022-04-08,True,True
17567,265.0,44.0,94.0,0.468,16.0,43.0,0.372,42.0,47.0,0.894,...,34.7,159.0,138.0,DEN,141,1,2022,2022-04-10,True,NaN

In [13]:
df["target"][pd.isnull(df["target"])] = 2

C:\Users\HP\AppData\Local\Temp\ipykernel_11000\1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [14]:
df["target"] = df["target"].astype(int, errors ="ignore")
df["won"] = df["won"].astype(int, errors ="ignore")

In [15]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,teams_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,1,1
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,0,1
2,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,1,1
3,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,0,0
4,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,40.0,91.0,0.440,15.0,43.0,0.349,12.0,15.0,0.800,...,32.4,205.0,120.0,BOS,97,1,2022,2022-06-10,1,1
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,1,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,0,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,0,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,1,2

In [16]:
df["won"].value_counts()

1    8886
0    8886
Name: won, dtype: int64

In [17]:
nulls = df.isnull().sum()

In [18]:
nulls = nulls[nulls>0]

In [19]:
nulls

+/-             17772
mp_max          17772
mp_max.1        17772
+/-_opp         17772
mp_max_opp      17772
mp_max_opp.1    17772
dtype: int64

In [20]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [21]:
df = df[valid_columns].copy()

In [22]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,teams_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,1,1
1,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,0,1
2,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,1,1
3,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,0,0
4,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,40.0,91.0,0.440,15.0,43.0,0.349,12.0,15.0,0.800,...,32.4,205.0,120.0,BOS,97,1,2022,2022-06-10,1,1
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,1,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,0,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,0,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,1,2

In [23]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [24]:
removed_cols = ["season", "date", "won", "target", "teams", "teams_opp"]

In [25]:

selected_cols = df.columns[~df.columns.isin(removed_cols)]

In [26]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_cols] = scaler.fit_transform(df[selected_cols])

In [27]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,teams_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.409091,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.150193,0.800948,0.517647,ATL,0.288462,1.0,2016,2015-10-27,1,1
1,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.317647,DET,0.403846,0.0,2016,2015-10-27,0,1
2,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.505882,NOP,0.298077,0.0,2016,2015-10-27,1,1
3,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.317647,GSW,0.451923,1.0,2016,2015-10-27,0,0
4,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.317647,CHI,0.317308,1.0,2016,2015-10-27,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.132221,0.549763,0.505882,BOS,0.317308,1.0,2022,2022-06-10,1,1
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.411765,BOS,0.288462,0.0,2022,2022-06-13,1,1
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.352941,GSW,0.384615,1.0,2022,2022-06-13,0,0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.400000,GSW,0.375000,0.0,2022,2022-06-16,0,2
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.576471,BOS,0.250000,1.0,2022,2022-06-16,1,2

In [28]:
sfs.fit(df[selected_cols], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [29]:
predictors = list(selected_cols[sfs.get_support()])

In [30]:
predictors

['mp',
 'fg%',
 'ft%',
 'ts%',
 'orb%',
 'usg%',
 '3p%_max',
 'ft_max',
 'fta_max',
 'tov_max',
 '+/-_max',
 'efg%_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'usg%_max',
 'mp_opp',
 '3p_opp',
 'blk_opp',
 'drb%_opp',
 'usg%_opp',
 'fga_max_opp',
 '3p_max_opp',
 'ft_max_opp',
 'stl_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 'ast%_max_opp',
 'stl%_max_opp']

In [42]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"]<season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train['target'])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actuals", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [43]:
predictions = backtest(df, rr, predictors)

In [44]:
predictions

       actuals  prediction
5250         1           0
5251         0           0
5252         1           1
5253         1           1
5254         0           0
...        ...         ...
17767        1           1
17768        1           1
17769        0           1
17770        2           0
17771        2           0

[12522 rows x 2 columns]

In [45]:
from sklearn.metrics import accuracy_score
predictions = predictions[predictions["actuals"]!=2]
accuracy_score(predictions["actuals"], predictions["prediction"])

0.5389849503682357

In [46]:
df.groupby("home").apply(lambda x:x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.428314
1.0    0.571686
dtype: float64

In [47]:
df_rolling = df[list(selected_cols) + ["won", "teams", "season"]]

In [49]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,teams,season
0,0.0,0.409091,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.071,0.550314,0.150193,0.800948,0.517647,0.288462,1.0,1,DET,2016
1,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.047,0.300839,0.019255,0.203791,0.317647,0.403846,0.0,0,ATL,2016
2,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.063,0.344864,0.215661,0.530806,0.505882,0.298077,0.0,1,GSW,2016
3,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.079,0.679245,0.277279,0.554502,0.317647,0.451923,1.0,0,NOP,2016
4,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.140,0.509434,0.160462,0.345972,0.317647,0.317308,1.0,0,CLE,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.070,0.222222,0.132221,0.549763,0.505882,0.317308,1.0,1,GSW,2022
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.124,0.423480,0.928113,1.000000,0.411765,0.288462,0.0,1,GSW,2022
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.076,0.300839,0.181001,0.630332,0.352941,0.384615,1.0,0,BOS,2022
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.063,0.300839,0.120668,0.459716,0.400000,0.375000,0.0,0,BOS,2022
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.160,1.000000,0.263158,0.246445,0.576471,0.250000,1.0,1,GSW,2022

In [56]:
def team_avg(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["teams", "season"], group_keys = False).apply(team_avg)

C:\Users\HP\AppData\Local\Temp\ipykernel_11000\84149631.py:2: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['teams'], dtype='object')
  rolling = team.rolling(10).mean()

In [57]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,season
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.502273,0.388235,0.500478,0.493103,0.501515,0.458789,0.309302,0.276190,0.741657,...,0.0737,0.1147,0.431761,0.242875,0.567773,0.575294,0.394231,0.4,0.7,2022.0
17768,0.0,0.502273,0.364706,0.517703,0.455172,0.481818,0.440736,0.320930,0.282540,0.757993,...,0.0716,0.1171,0.374109,0.321566,0.642654,0.564706,0.392308,0.4,0.7,2022.0
17769,0.0,0.354545,0.279412,0.404545,0.437931,0.465152,0.429572,0.434884,0.385714,0.736639,...,0.0591,0.1113,0.483229,0.174711,0.438863,0.483529,0.350000,0.5,0.5,2022.0
17770,0.0,0.354545,0.294118,0.389952,0.434483,0.459091,0.431710,0.406977,0.357143,0.754142,...,0.0572,0.1111,0.483229,0.172144,0.460190,0.472941,0.344231,0.5,0.5,2022.0
17771,0.0,0.484091,0.379412,0.482297,0.486207,0.507576,0.448812,0.316279,0.269841,0.801750,...,0.0656,0.1152,0.444025,0.308601,0.628910,0.568235,0.395192,0.5,0.7,2022.0

In [59]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis=1)

In [60]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
0,0.0,0.409091,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.0737,0.1147,0.431761,0.242875,0.567773,0.575294,0.394231,0.4,0.7,2022.0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.0716,0.1171,0.374109,0.321566,0.642654,0.564706,0.392308,0.4,0.7,2022.0
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.0591,0.1113,0.483229,0.174711,0.438863,0.483529,0.350000,0.5,0.5,2022.0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.0572,0.1111,0.483229,0.172144,0.460190,0.472941,0.344231,0.5,0.5,2022.0
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.0656,0.1152,0.444025,0.308601,0.628910,0.568235,0.395192,0.5,0.7,2022.0

In [61]:

df = df.dropna()

In [62]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10
224,0.0,0.522727,0.382353,0.523923,0.344828,0.333333,0.457245,0.255814,0.238095,0.708285,...,0.0628,0.0679,0.413522,0.124134,0.361611,0.449412,0.347115,0.4,0.8,2016.0
249,0.0,0.659091,0.426471,0.645933,0.620690,0.515152,0.562945,0.325581,0.238095,0.927655,...,0.0613,0.0772,0.469497,0.219641,0.394787,0.531765,0.324038,0.5,1.0,2016.0
252,0.0,0.295455,0.235294,0.363636,0.344828,0.348485,0.439430,0.627907,0.476190,0.886814,...,0.0747,0.0742,0.303564,0.130552,0.387678,0.410588,0.350962,0.5,0.5,2016.0
259,0.0,0.500000,0.382353,0.497608,0.344828,0.318182,0.475059,0.325581,0.349206,0.593932,...,0.0646,0.0759,0.512159,0.133633,0.277251,0.388235,0.308654,0.4,0.6,2016.0
260,0.0,0.477273,0.500000,0.375598,0.379310,0.348485,0.483373,0.441860,0.396825,0.730455,...,0.0657,0.1032,0.437212,0.124904,0.404739,0.408235,0.428846,0.2,0.3,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.0737,0.1147,0.431761,0.242875,0.567773,0.575294,0.394231,0.4,0.7,2022.0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.0716,0.1171,0.374109,0.321566,0.642654,0.564706,0.392308,0.4,0.7,2022.0
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.0591,0.1113,0.483229,0.174711,0.438863,0.483529,0.350000,0.5,0.5,2022.0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.0572,0.1111,0.483229,0.172144,0.460190,0.472941,0.344231,0.5,0.5,2022.0
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.0656,0.1152,0.444025,0.308601,0.628910,0.568235,0.395192,0.5,0.7,2022.0

In [65]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col
def add_col(df, col_name):
    return df.groupby("teams", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["teams_opp_next"] = add_col(df, "teams_opp")
df["date_next"] = add_col(df, "date")

C:\Users\HP\AppData\Local\Temp\ipykernel_11000\242932249.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df.copy(), "home")
C:\Users\HP\AppData\Local\Temp\ipykernel_11000\242932249.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["teams_opp_next"] = add_col(df.copy(), "teams_opp")
C:\Users\HP\AppData\Local\Temp\ipykernel_11000\242932249.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df.copy(), "date")

In [66]:
df = df.copy()

In [67]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,season_10,home_next,teams_opp_next,date_next
224,0.0,0.522727,0.382353,0.523923,0.344828,0.333333,0.457245,0.255814,0.238095,0.708285,...,0.124134,0.361611,0.449412,0.347115,0.4,0.8,2016.0,0.0,BOS,2015-11-13
249,0.0,0.659091,0.426471,0.645933,0.620690,0.515152,0.562945,0.325581,0.238095,0.927655,...,0.219641,0.394787,0.531765,0.324038,0.5,1.0,2016.0,1.0,BRK,2015-11-14
252,0.0,0.295455,0.235294,0.363636,0.344828,0.348485,0.439430,0.627907,0.476190,0.886814,...,0.130552,0.387678,0.410588,0.350962,0.5,0.5,2016.0,0.0,WAS,2015-11-14
259,0.0,0.500000,0.382353,0.497608,0.344828,0.318182,0.475059,0.325581,0.349206,0.593932,...,0.133633,0.277251,0.388235,0.308654,0.4,0.6,2016.0,0.0,CHI,2015-11-16
260,0.0,0.477273,0.500000,0.375598,0.379310,0.348485,0.483373,0.441860,0.396825,0.730455,...,0.124904,0.404739,0.408235,0.428846,0.2,0.3,2016.0,1.0,TOR,2015-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.242875,0.567773,0.575294,0.394231,0.4,0.7,2022.0,1.0,BOS,2022-06-13
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.321566,0.642654,0.564706,0.392308,0.4,0.7,2022.0,0.0,BOS,2022-06-16
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.174711,0.438863,0.483529,0.350000,0.5,0.5,2022.0,1.0,GSW,2022-06-16
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.172144,0.460190,0.472941,0.344231,0.5,0.5,2022.0,NaN,NaN,NaN
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.308601,0.628910,0.568235,0.395192,0.5,0.7,2022.0,NaN,NaN,NaN

In [69]:
full = df.merge(df[rolling_cols + ["teams_opp_next", "date_next", "teams"]], 
               left_on = ["teams", "date_next"], 
               right_on = ["teams_opp_next", "date_next"]
)

In [70]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,season_10_y,teams_opp_next_y,teams_y
0,0.00,0.477273,0.500000,0.375598,0.379310,0.348485,0.483373,0.441860,0.396825,0.730455,...,0.380294,0.273427,0.270616,0.478824,0.308654,0.6,0.7,2016.0,SAC,TOR
1,0.00,0.340909,0.250000,0.413876,0.310345,0.257576,0.509501,0.511628,0.412698,0.827305,...,0.437212,0.124904,0.404739,0.408235,0.428846,0.2,0.3,2016.0,TOR,SAC
2,0.25,0.500000,0.558824,0.356459,0.068966,0.212121,0.131829,0.325581,0.238095,0.927655,...,0.421593,0.133504,0.345498,0.454118,0.343269,0.4,0.7,2016.0,BRK,ATL
3,0.00,0.545455,0.426471,0.511962,0.275862,0.363636,0.339667,0.348837,0.317460,0.722287,...,0.427568,0.258280,0.514218,0.335294,0.390385,0.5,0.0,2016.0,DAL,PHI
4,0.00,0.318182,0.323529,0.318182,0.275862,0.272727,0.432304,0.186047,0.158730,0.787631,...,0.310377,0.127086,0.312796,0.410588,0.353846,0.5,0.6,2016.0,PHI,DAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15769,0.00,0.386364,0.264706,0.461722,0.517241,0.545455,0.445368,0.279070,0.222222,0.844807,...,0.452516,0.166624,0.444076,0.531765,0.358654,0.6,0.6,2022.0,GSW,BOS
15770,0.00,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.431761,0.242875,0.567773,0.575294,0.394231,0.4,0.7,2022.0,BOS,GSW
15771,0.00,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.471908,0.170603,0.431754,0.522353,0.348077,0.5,0.6,2022.0,GSW,BOS
15772,0.00,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.483229,0.174711,0.438863,0.483529,0.350000,0.5,0.5,2022.0,GSW,BOS
15773,0.00,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.374109,0.321566,0.642654,0.564706,0.392308,0.4,0.7,2022.0,BOS,GSW

In [71]:
removed_cols = list(full.columns[full.dtypes == "object"]) + removed_cols

In [72]:
removed_cols

['teams_x',
 'teams_opp',
 'date',
 'teams_opp_next_x',
 'date_next',
 'teams_opp_next_y',
 'teams_y',
 'season',
 'date',
 'won',
 'target',
 'teams',
 'teams_opp']

In [74]:
selected_cols = full.columns[~full.columns.isin(removed_cols)]

In [75]:
sfs.fit(full[selected_cols], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [77]:
predictors = list(selected_cols[sfs.get_support()])

In [ ]:
predictions = backtest(full, rr, predictors)

In [78]:
accuracy_score(predictions["actual"], predictions["prediction"])

KeyError: 'actual'